### ISSUE TITLE
Check if an odometry calibration is needed

### ISSUE THREAD

**Issue by eborghi10** [RoboticaUtnFrba/create_autonomy#57]
- [Odometry Calibration by Least Squares](http://ais.informatik.uni-freiburg.de/teaching/ws10/robotics2/pdfs/rob2-05-odometry-calib-practical.pdf)

### Turtlebot (with Create base) calibration

- ROS package used: [`turtlebot_calibration`](https://wiki.ros.org/turtlebot_calibration)
- [TutorialCreate Odometry and Gyro Calibration](https://wiki.ros.org/turtlebot_calibration/Tutorials/Calibrate%20Odometry%20and%20Gyro)
- [The tutorial executes this launch file](https://github.com/turtlebot/turtlebot_apps/blob/indigo/turtlebot_calibration/launch/calibrate.launch#L12-L22)
- But the video refers to [this file](https://github.com/Arkapravo/turtlebot/blob/master/turtlebot_node/nodes/turtlebot_node.py#L318)
- Look how [this code](https://github.com/Arkapravo/turtlebot/blob/88e910d252adfa3b8da145ec63fda436bcb2ecc0/turtlebot_node/src/turtlebot_node/gyro.py#L51) uses the gyro.
- How is the gyro fused with the wheel odometry now?
- [UMBmark calibration method](http://thetechnicgear.com/2014/06/howto-calibrate-differential-drive-robot/)
- [Where am I?](http://www-personal.umich.edu/~johannb/Papers/pos96rep.pdf)

- [Visualize elipsoid with RTEllipsoidFit.m](https://github.com/jetsonhacks/RTIMULib/blob/master/RTEllipsoidFit/RTEllipsoidFit.m)
- [Calibrate IMU with RTIMULib](https://github.com/RoboticaUtnFrba/RTIMULib/blob/master/Calibration.pdf)

----

- Working branches: 
    - [`robot_calibration`](https://github.com/RoboticaUtnFrba/create_autonomy/tree/eborghi/robot_calibration)
    - [Wheel odometry mismatches](https://github.com/RoboticaUtnFrba/create_autonomy/compare/kinetic-devel...RoboticaUtnFrba:eborghi/wheel_odometry), [`libcreate` changes](https://github.com/RoboticaUtnFrba/libcreate/compare/master...RoboticaUtnFrba:eborghi/wheel_odometry)

**TODO:**

- [ ] Test it with the real robot
- [ ] Address changes that were written in the code
- [ ] Wheel odometry doesn't report the correct body velocity
